// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reshare_proto_0._2.Repository;

namespace Reshare_proto_0._2.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reshare_proto_0._2.Models.CategoryModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("tblCategory");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.ImageCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageModelImgId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageModelImgId");

                    b.ToTable("tblImageCategories");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.ImageModel", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImgId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Url");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ImgId");

                    b.HasIndex("UserId");

                    b.ToTable("tblImages");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.LocationModel", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CoountryId")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.ToTable("tblLocation", "dim");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhoneNbr");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.ToTable("tblUser");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.UserSaveModel", b =>
                {
                    b.Property<int>("UserSaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("UserModelUserId")
                        .HasColumnType("int");

                    b.HasKey("UserSaveId");

                    b.HasIndex("UserModelUserId");

                    b.ToTable("tblUserSaves");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.ImageCategoryModel", b =>
                {
                    b.HasOne("Reshare_proto_0._2.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reshare_proto_0._2.Models.ImageModel", null)
                        .WithMany("ImageCategories")
                        .HasForeignKey("ImageModelImgId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.ImageModel", b =>
                {
                    b.HasOne("Reshare_proto_0._2.Models.UserModel", "User")
                        .WithMany("Images")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.UserModel", b =>
                {
                    b.HasOne("Reshare_proto_0._2.Models.LocationModel", "Location")
                        .WithOne("User")
                        .HasForeignKey("Reshare_proto_0._2.Models.UserModel", "LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.UserSaveModel", b =>
                {
                    b.HasOne("Reshare_proto_0._2.Models.UserModel", null)
                        .WithMany("UserSaves")
                        .HasForeignKey("UserModelUserId");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.ImageModel", b =>
                {
                    b.Navigation("ImageCategories");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.LocationModel", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Reshare_proto_0._2.Models.UserModel", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("UserSaves");
                });
#pragma warning restore 612, 618
        }
    }
}
